import pandas
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

url = "./recipes_output.csv"
names = ["shortening",
         "sugar",
         "sour milk",
         "soda water",
         "flour",
         "baking powder",
         "chopped nuts",
         "cream cheese",
         "eggs",
         "lemon juice",
         "vanilla",
         "butter",
         "milk",
         "blueberries",
         "margarine",
         "cocoa",
         "salt",
         "baking soda",
         "cloves",
         "Best Foods Mayonnaise",
         "water",
         "lemon cake mix",
         "lemon jello",
         "vegetable oil",
         "powdered sugar",
         "diced apples",
         "eggs, well beaten",
         "cinnamon",
         "pears",
         "graham crackers, crushed",
         "wheat germ, optional",
         "graham cracker crumbs",
         "melted butter",
         "sour cream",
         "cottage cheese",
         "lemon instant pudding",
         "oil",
         "poppy seeds",
         "sifted flour",
         "nutmeg",
         "whole pecans",
         "canned pineapple, chopped",
         "whole canned cherries",
         "golden raisins",
         "brandy flavoring",
         "egg",
         "molasses",
         "soda",
         "ginger",
         "hot water",
         "oatmeal",
         "angel food cake mix",
         "frozen orange juice concentrate, thawed",
         "frozen light whipped topping, thawed",
         "plain low fat yogurt",
         "unsalted butter, softened",
         "grated orange peel",
         "unsifted cake flour",
         "fresh orange juice",
         "crushed pineapple",
         "yellow cake mix",
         "sliced almonds",
         "crushed pineapple, drained",
         "grated carrots",
         "chopped walnuts",
         "mashed potatoes",
         "eggs, beaten separately",
         "vanilla wafer crumbs",
         "melted margarine",
         "lite cream cheese",
         "pumpkin",
         "cornflakes",
         "gelatin",
         "cold water",
         "eggs, separated",
         "grated lemon rind",
         "heavy cream",
         "instant vanilla pudding",
         "sherry cooking wine",
         "nutmeg, cinnamon, and allspice",
         "buttermilk",
         "cooked prunes",
         "white corn syrup",
         "chopped pitted prunes",
         "walnuts",
         "allspice",
         "unsalted butter",
         "berries",
         "brown sugar",
         "fruit juice",
         "cold butter",
         "chocolate chips",
         "semisweet chocolate chips",
         "light corn syrup",
         "bourbon (or light cream)",
         "crushed vanilla wafers",
         "finely chopped walnuts",
         "All-Bran cereal",
         "crunchy peanut butter",
         "egg yolk, beaten",
         "Special K cereal",
         "light brown sugar",
         "coconut",
         "crushed walnuts",
         "pitted dates",
         "flake coconut",
         "butter or margarine",
         "raisins (or finely diced prunes or dates)",
         "rolled oats",
         "granulated sugar",
         "egg white, stiffly beaten",
         "whole wheat flour",
         "honey",
         "fruit jello",
         "lemon peel",
         "Lemon juice",
         "mint apple jelly",
         "raisin liquid",
         "soda, dissolved in raisin liquid",
         "oats",
         "raisins, boiled 20 min.",
         "all-spice",
         "light brown sugar, firmly packed",
         "quick-cooking oats",
         "walnuts, chopped",
         "semi-sweet chocolate chips",
         "sweetened condensed milk",
         "peanut butter",
         "egg ",
         "crushed pineapple, drained.",
         "pitted prunes",
         "confectioner's sugar",
         "nuts",
         "raisins",
         "pumpkin pie spice",
         "cream of tartar",
         "cinnamon and sugar",
         "Crisco (shortening)",
         "nuts, chopped",
         "baked pastry shell",
         "cornstarch",
         "egg yolks, beaten",
         " margarine or butter",
         "bananas",
         "lemon juice from concentrate",
         "whipped cream",
         "blackberries",
         "nectarines, sliced",
         "baked pie shell",
         "pie shell, unbaked",
         "tart apples, peeled and sliced",
         "large apples, sliced",
         "red food coloring",
         "strawberries",
         "pie shell, baked",
         "lemon rind, grated",
         "graham cracker crust",
         "egg yolks, slightly beaten",
         "pie shell",
         "lemon juice, fresh or bottled",
         "grated lemon juice",
         "egg yolks",
         "egg whites",
         "sliced",
         "fresh peaches, sliced",
         "almond extract",
         "peach or lemon gelatin",
         "Peach or vanilla ice cream",
         "fresh peaches, peeled and diced",
         "baked pie shell, chilled",
         "graham cracker crumbs, 18 squares",
         "margarine, melted",
         "whipped cream or cool whip",
         "vanilla ice cream",
         "chunk style peanut buter",
         "light or dark corn syrup",
         "eggs, slightly beaten",
         "chunk style peanut butter",
         "ice water or 7-up",
         "evaporated milk",
         "pineapple juice",
         "Dream Whip or whipped cream",
         "pineapple tidbits",
         "marshmallows",
         "bananas, sliced",
         "blue cheese",
         "mayonnaise",
         "white sauterne wine",
         "garlic powder",
         "accent seasoning mix",
         "broccoli, cut into small pieces",
         "red onion",
         "sunflower seed",
         "stalks of celery",
         "red wine vinegar ",
         "curry, to taste",
         "broccoli florets, bite size",
         "mozzarella cheese, shredded",
         "red onion, chopped",
         "crisp bacon, crumbled",
         "vinegar",
         "bacon, but small, fry until crisp",
         "broccoli",
         "crushed pineapple, well drained",
         " red onion, chopped fine",
         "sunflower seeds",
         "Knox Unflavored Gelatin",
         "cold orange juice, divided",
         "boiling orange juice",
         "salad dressing",
         "carrot pieces",
         "cabbage",
         "horseradish",
         "salt and pepper",
         "caraway seed (optional)",
         "cherry jello, or 1 large",
         "whole cranberry sauce",
         "cucumbers, sliced",
         "pepper",
         "chives or scallions, minced",
         "green beans",
         "wax beans",
         "kidney beans",
         "garbanzo beans",
         "bean sprouts",
         "red onion, sliced",
         "pineapple chunks",
         "mandarin oranges",
         "asparagus",
         "cauliflower",
         "green onions",
         "radishes",
         "peeled tomato",
         "avacado",
         "fresh mushrooms",
         "pasta",
         "Italian Dressing",
         "fresh beans",
         "salad oil",
         "white vinegar",
         "pineapple juice + water",
         "onion powder",
         "kelp",
         "Dream Whip",
         "frozen lima beans",
         "fresh mushrooms, sliced",
         "green onions, sliced",
         "parsley, choped",
         "oregano",
         "garlic, crushed",
         "frozen peas, uncooked",
         "green onion, chopped",
         "crumbled bacon bits",
         "water chestnuts, sliced",
         "salted cashew pieces.",
         "salt and  pepper to taste",
         "dry mustard",
         "paprika",
         "spinach leaves",
         "onion, red is best",
         "bacon",
         "egg, slightly beaten",
         "egg, hard-boiled",
         "fresh spinach",
         "avocado",
         "olive oil",
         "bacon, crisp and crumbled",
         "spinach greens",
         "sliced onion",
         "alfalfa sprouts",
         "bacon bits",
         "grated jack cheese",
         "catsup",
         "pineapple chunks in juice",
         "seedless grapes",
         "cantaloupe, cut into chunks",
         "watermelon chunks",
         "chicken Ramen",
         "salad greens",
         "frozen peas",
         "caraway seed",
         "zucchini, coarsely shredded",
         "tart apples, cut in chunks",
         "potato (2-3 cups), peeled and diced",
         "broccoli florets, cut or broken",
         "carrot, peeled and chopped",
         "cloves of garlic, peeled",
         "onion, chopped",
         "cheddar cheese, grated",
         "low-fat milk",
         "dill",
         "chicken, cooked and chopped",
         "potato, diced",
         "carrots, diced",
         "celery, sliced",
         "chicken bouillion",
         "poultry seasoning",
         "salt, to taste",
         "narrow egg noodles",
         "bacon, chopped and browned",
         "onion, suated",
         "celery, sauted",
         "potatoes, peeled and diced",
         "half and half",
         "thyme or basil",
         "chopped clams with juice",
         "zucchini, thinly sliced (about 3/4 lb.)",
         "garlic, minced",
         "cream of mushroom soup, condensed",
         "fresh oregano, chopped or 1/4 tsp dried",
         "fresh basil, or 1/4 tsp dried",
         "ground pepper, to taste",
         "pine nuts, toasted",
         "elephant",
         "salt and pepper to taste",
         "brown gravy",
         "rabbits",
         "hamburger",
         "potatoes, diced",
         "onion, coarsely chopped",
         "stewed tomatoes, crushed",
         "tomatoes, crushed",
         "tomato sauce",
         "instant rice",
         "potatoes, cubed",
         "stalks of celery, chopped",
         "frozen spinach",
         "zucchini, diced",
         "cabbage, chopped",
         "stewed tomatoes",
         "spaghetti sauce mix",
         "broken spaghetti",
         "lime",
         "ground cumin",
         "diced oregano leaves, crushed",
         "Campbell's condensed chicken broth",
         "tomato, chopped",
         "chopped green chiles",
         "corn tortillas",
         "monterey jack or cheddar cheese, shredded",
         "lettuce, shredded",
         "peanut or vegetable oil",
         "b1d and skinned chicken breasts, cut into 1 inch pieces",
         "red or green pepper, cut in thin strips",
         "chicken broth",
         "sherry",
         "soy sauce",
         "b1d chicken breast cut into 1-inch cubes",
         "celery, bite size",
         "onion",
         "mushroom",
         "green pepper",
         "flank steak",
         "tomatoes",
         "green peppers",
         "garlic",
         "ground ginger",
         "broccoli florets",
         "crab or shrimp",
         "bea10 egg white",
         "dry sherry",
         "orange peel",
         "anise",
         "chicken breast, poached 15 minutes",
         "slivered green onions",
         "slivered lettuce",
         "diced ham, pork or chicken",
         "sliced mushrooms (optional)",
         "chopped green onions",
         "cold cooked rice",
         "tbsp",
         "round steak, cut 1 inch thick",
         "sauce",
         "peppers",
         "tomatoes, halved",
         "h1y",
         "chicken bouillon",
         "fresh pork butt or shoulder of pork",
         "b1less chicken, cut in cubes",
         "ginger root",
         "crushed red pepper",
         "unsalted peanuts",
         "rice vinegar",
         "mexican blend cheese",
         "salsa",
         "spinach",
         "chopped artichoke hearts",
         "cumin",
         "tortilla chips",
         "oranges",
         "unsalted beef boullion",
         "minced garlic",
         "celery",
         "rice",
         "Ribs",
         "barbeque sauce",
         "sausage",
         "accent",
         "chopped onion",
         "bread crumbs",
         "boullion",
         "ketchup",
         "medium-size raw shrimp, peeled and deveined",
         "minced ginger",
         "green bell pepper, chunked",
         "medum onion, chunked",
         "celery, thinly sliced diagonally",
         "chinese noodle cakes",
         "fish fillets",
         "margerine",
         "lemon juice or sherry",
         "grated cheese",
         "sliced mushrooms",
         "slices bacon for each",
         "onion, thinly sliced",
         "bay leaf, crumbled",
         "fine cracker crumbs",
         "red pepper",
         "white pepper",
         "shredded Swiss or cheddar cheese",
         "spinach, thawed and well-drained",
         "fish fillets, cut in serving pieces",
         "grated parmesan cheese",
         "melted Mexican blend cheese",
         "chopped spinach",
         "artichoke hearts",
         "scallops",
         "very fine bread crumbs",
         "minced onion",
         "lemon juice or white wine",
         "linguini",
         "chopped clams",
         "white wine with clam juice and enough half-and-half to make 2 cups of liquid",
         "chopped parsley",
         "dried thyme",
         "sole filets",
         "almonds, sliced thin",
         "white wine",
         "mayonaise",
         "worchester",
         "crab meat",
         "cheddar cheese",
         "raw shrimp, peeled and deveined",
         "green pepper, chopped",
         "cloves, minced",
         "linguini or spaghetti",
         "grated Romano cheese",
         "fresh parsely, chopped",
         "lemon slices",
         "fresh ginger, grated",
         "garlic, finely chopped",
         "onion, cut in thin wedges",
         "water or chicken stock",
         "chili powder",
         "celery salt",
         "worchestershire sauce",
         "garlic, chopped",
         "lemon, sliced thinly",
         "pork 10derloin",
         "chicken coasting mix",
         "ice water",
         "egg yolk",
         "beef round steak",
         "tomatoes, blanched",
         "green onions, chopped",
         "basil",
         "veal steak, sliced thinly",
         "sauterne wine",
         "sliced onions",
         "wesson oil",
         "steak, cubed",
         "hot buttered noodles",
         "tomatoes, canned",
         "thyme",
         "veal, sliced thinly",
         "egg, bea10",
         "mozzarella, sliced thinly",
         "parmesan",
         "round steak",
         "mushroom soup",
         "mushrooms, sliced",
         "wheat germ (optional)",
         "butter, melted",
         "cabbage, finely shredded",
         "water chestnuts, finely chopped",
         "bamboo shoots, finely chopped",
         "egg roll wrappers",
         "egg, slightly bea10",
         "pineapple chunks, injuice",
         "green pepper (optional)",
         "ribs",
         "onion, chopped quite large",
         "celery, cut into large chunks",
         "cooked pork, cubed",
         "mushroom soup or leftover pork gravy",
         "pea pods, frozen",
         "chinese noodles",
         "precooked rice, cook overnight",
         "shrimp",
         "green onions, diced",
         "pineapple",
         "pork 10derloin, cut into chunks",
         "chicken coating mix",
         "green pepper, sliced",
         "carrot, diagonally sliced",
         "lemon",
         "pinapple chunks",
         "chickens, cut in pieces",
         "onion, minced",
         "parsley",
         "chicken breast halves, b1d and skinned",
         "garlic salt",
         "cornmeal",
         "avocado, peeled and sliced",
         "monteray jack cheese, shredded",
         "green onion tops, sliced",
         "red pepper, chopped",
         "cherry tomatoes",
         "parsley sprigs",
         "flour, sifted",
         "seas1d salt",
         "chicken, cut up",
         "oil, for cooking",
         "catalina french dressing",
         "b1less, skinless chicken breast, cubed",
         "any frozen mixed vegetable, thawed",
         "leaf spinach, cut",
         "skinless b1less chicken breasts, cut in 1/2",
         "dry bread crumbs",
         "basil leaves",
         "shredded mozzarella cheese",
         "chicken breasts",
         "pea pods, fresh or frozen",
         "bamboo shoots, drained",
         "chicken boullion",
         "cashews",
         "chicken breast, sliced and marinated",
         "green onion, sliced",
         "mushrooms",
         "pea pods",
         "cayenne",
         "chicken, skinned and b1d",
         "garlic, large",
         "bread crumbs, dried",
         "chicken cutlets, pounded to 1/8 inch thick",
         "eggs, lightly bea10",
         "apples, cored, pared, thinly sliced",
         "sauerkraut",
         "lemons, thinly sliced",
         "chicken breast, split",
         "chicken thighs",
         "artichokes",
         "onion, grated",
         "chicken",
         "pork shoulder steak, cut into 1/2 inch cubes",
         "boiling onions",
         "dry red wine",
         "dijon mustard",
         "cornstarch and water",
         "parsely, chopped",
         "miracle whip",
         "broccoli, chopped",
         "Velveeta",
         "skinless b1less chicken breasts",
         "white onions, chopped",
         "curry powder",
         "broccoli florets, bite size pieces",
         "cooking apple, cored and chopped",
         "chopped peanuts",
         "zucchini",
         "freshly ground pepper",
         "jack cheese",
         "broiler chicken, cut up",
         "all-purpose flour",
         "chicken parts",
         "cream of mushroom soup",
         "parsley, chopped",
         "crushed stuffing mix",
         "Italian salad dressing",
         "parmasen cheese",
         "marinated artichoke hearts",
         "salt, pepper, flour",
         "Uncle Ben's Converted Rice",
         "slivered ham",
         "mashed garlic",
         "can Italian style tomatoes",
         "red wine",
         "Italian seasoning",
         "chicken breasts, skinned and b1d",
         "wine cooler",
         "bouillon",
         "cooked rice",
         "chicken livers",
         "onions, minced",
         "dry white wine",
         "chicken wings or drumettes",
         "Louisiana-style hot sauce",
         "melted butter or margarine",
         "turkey breast 10derloins",
         "onion, sliced into rings",
         "cream of chicken soup",
         "swiss cheese, shredded",
         "hot cooked rice or noodles",
         "sparagus",
         "fresh ginger, minced",
         "chicken stock",
         "fresh green beans",
         "dried tarragon",
         "mushrooms, rinsed",
         "zucchini, shredded",
         "fine dried bread crumbs",
         "parmasen cheese, grated",
         "dried oregano",
         "green onion, minced",
         "eggs, slightly bea10",
         "monterey jack cheesed, shredded",
         "cumin seed, crushed",
         "dried oregano, crushed",
         "eggs, bea10",
         "white bread, cubed",
         "green onion",
         "parmesan cheese",
         "cabbage, shredded",
         "red potatoes",
         "potatoes, unpeeled",
         "onions",
         "celery seed",
         "egg, seperated",
         "ricotta cheese",
         "mozzarella or provol1, coarsely grated",
         "fresh parsley, chopped",
         "eggplant",
         "red wine vinaigrette",
         "marinara sauce",
         "dried basil",
         "carrots",
         "spoonful of orange marmalade",
         "package of dry spaghetti sauce mix",
         "green beans, dried",
         "shredded lettuce",
         "rosemary",
         "savory salt",
         "bacon, cut up",
         "worcestershire sauce",
         "toast slices",
         "sweet potatoes",
         "oranges, sliced thin",
         "frozen peas, cooked",
         "small onions",
         "parsley flakes",
         "crisply fried bacon bits",
         "phyllo pastry",
         "onion, finely chopped",
         "frozen chopped spinach, thawed and drained",
         "feta cheese, crumbled",
         "fresh dill, chopped",
         "butter or margarine, melted",
         "eggs, seperated",
         "spinach, cooked",
         "fresh spinach, stems removed",
         "shallots, chopped",
         "gorgonzola cheese, crumbled",
         "cream cheese, sof10ed",
         "phyllo pastry sheets",
         "unsalted butter, melted",
         "hamburger or sausage",
         "croutons",
         "boullion cube",
         "sage",
         "summer squash",
         "butter salt",
         "cracker crumbs",
         "bacon bits, crisply fried",
         "red cabbage, shredded",
         "unparred apple, cubed",
         "frozen spinach, chopped",
         "bacon, cut into 1/2 inch dice",
         "onions, chopped",
         "beef stock base or a boullion cube",
         "mushroom stems and pieces, drained",
         "frozen chopped spinach",
         "low fat cottage cheese",
         "eggs, lightly beaten",
         "grated swiss cheese",
         "frozen hashbrown potatoes, thawed",
         "dried onions or 1/2 cup fresh",
         "cream of chcken soup",
         "cornflakes, crushed",
         "apples, peeled, cut in 1/4",
         "egg yolk, plus enough milk to make 1/2 cup",
         "tart apples, sliced",
         "whole prunes",
         "pecans, chopped",
         "peaches, sliced",
         "small marshmallows",
         "vanilla wafers, crushed",
         "knox gelatin",
         "fresh peaches (or frozen, thawed), sliced",
         "sugar, divided",
         "almond flavoring",
         "garlic, pressed",
         "parsley, minced",
         "leaf oregano",
         "artichoke hearts, drained, finely chopped",
         "hot pepper liquid",
         "10 inch pie shell, partially baked",
         "eggs, beaten",
         "fresh aparagus spears, washed and trimmed",
         "tomato, sliced into four 1/4 slices",
         "beef",
         "red kidney beans",
         "tortillas",
         "beef bouillon",
         "boiling water",
         "10 inch  baked pie shell",
         "onion, diced",
         "spinach, drained",
         "cheese",
         "minute rice, uncooked",
         "frozen broccoli, chopped",
         "celery, chopped",
         "Cheeze Whiz",
         "fresh broccoli",
         "pepper sauce",
         "swiss cheese",
         "bread",
         "boned chicken breasts, cooked, cut into bite-size",
         "bacon, chopped",
         "yellow cornmeal",
         "cayenne pepper",
         "creamed corn",
         "sliced olives",
         "jack cheese, shredded",
         "diced green chiles",
         "medium noodles",
         "cream of mushroom soup or 2 cans cream of mushroom and 1 can chicken broth",
         "jar pimentos",
         "chicken, cooked and boned, cut into bite-size pieces",
         "tuna in oil",
         "cashew nuts",
         "chow mein noodles",
         "oregano or italian seasoning",
         "Chef Boyardee package pizza mix",
         "tomatoes, drained and chopped",
         "mushroom stems and pieces",
         "jack and mozzarella cheese, shredded",
         "ground beef",
         "cooked pasta",
         "spaghetti sauce",
         "elbow macaroni, cooked",
         "left-over beef, cubed",
         "cubed cheese",
         "Bisquick baking mix",
         "fresh or frozen broccoli, chopped",
         "french fried onions, ",
         "whipping cream",
         "taco seasoning mix",
         "chopped green chiles, drained",
         "fresh basil or parsley, crushed",
         "red or green pepper, cut up",
         "reduced calorie mayonnaise",
         "parmesan cheese, grated",
         "ground red pepper",
         "ground black pepper",
         "fettucine or linguine",
         "carrots, julienned",
         "cooked chicken or turkey breast, cut into strips",
         "ground chuck",
         "Lipton onion soup mix",
         "pork and beans in tomato sauce",
         "kidney beans, drained",
         "prepared mustard",
         "cider vinegar",
         "chicken pieces",
         "carrots, cut into chunks",
         "shredded cheese",
         "enchilada sauce",
         "clove garlic, minced",
         "swiss cheese, grated",
         "fresh ripe tomato",
         "lasagna noodles",
         "shallots, finely chopped",
         "button mushrooms, chopped",
         "shitake mushrooms, chopped",
         "gorgonzola, crumbled",
         "fresh parmesan, grated",
         "tomato paste",
         "frozen chopped spinach, thaw and squeeze dry",
         "grated nutmeg",
         "small zucchini",
         "butter, divided",
         "cheese, shredded",
         "onion, sliced thinly",
         "zucchini, sliced",
         "cooked slivered ham, optional",
         "recipe"
         ]
dataset = pandas.read_csv(url, names=names)
# Split-out validation dataset
array = dataset.values
X = array[:,0:795]
Y = array[:,795]
validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, Y, test_size=validation_size, random_state=seed)
scoring = 'accuracy'

# Spot Check Algorithms
models = []
models.append(('LR', LogisticRegression(solver='liblinear', multi_class='ovr')))
# models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC(gamma='auto')))
# evaluate each model in turn
results = []
names = []
for name, model in models:
	kfold = model_selection.KFold(n_splits=10, random_state=seed)
	cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring=scoring)
	results.append(cv_results)
	names.append(name)
	msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
	print(msg)


# Compare Algorithms
fig = plt.figure()
fig.suptitle('Algorithm Comparison')
ax = fig.add_subplot(111)
plt.boxplot(results)
ax.set_xticklabels(names)
plt.savefig('compare.pdf')
